####
# GitVersion.cmake:
#
# Generates `SamdHealthVersion.hpp`, a header holding the HEAD commit of each of the three
# git repositories that make up a flashed image:
#
#   - the project    (FPRIME_PROJECT_ROOT, e.g. moonfall-power-manager)
#   - the framework  (FPRIME_FRAMEWORK_PATH, i.e. lib/fprime)
#   - this library   (lib/fprime-samd)
#
# `SamdHealth` reports these over the `SystemInfo` event and `Info` channel, whose FPP
# fields are `U64`. A SHA-1 does not fit in 64 bits, so each is truncated to its leading 16
# hex digits -- a superset of any abbreviated hash git itself would print, so the value
# stays usable with `git show <hex>`.
#
# This file is meant to be run in script mode so that the stamp can be refreshed at build
# time without re-configuring:
#
#   cmake -DOUTPUT_FILE=... -DPROJECT_DIR=... -DFPRIME_DIR=... -DSAMD_DIR=... \
#         -DGIT_EXECUTABLE=... -P GitVersion.cmake
#
# The output file is only rewritten when its contents change, so a no-op build does not
# force a recompile of the component.
#
# A missing git, or a source tree that is not a repository, is not an error: the affected
# commit is reported as 0 and a warning is issued. A version stamp must never break a
# build.
####
cmake_minimum_required(VERSION 3.16)

####
# Function `samd_health_git_commit`:
#
# Reads the HEAD commit of the repository at REPOSITORY_DIR.
#
# - **REPOSITORY_DIR**: directory to introspect
# - **LABEL**: human-readable name of the repository, used in warnings
# - **COMMIT_VAR**: output variable, set to the leading 16 hex digits of HEAD, or `0`
# - **DESCRIPTION_VAR**: output variable, set to a human-readable summary of the repository
####
function(samd_health_git_commit REPOSITORY_DIR LABEL COMMIT_VAR DESCRIPTION_VAR)
    set("${COMMIT_VAR}" "0" PARENT_SCOPE)
    set("${DESCRIPTION_VAR}" "unavailable" PARENT_SCOPE)

    if (NOT GIT_EXECUTABLE)
        message(WARNING "[SamdHealth] git not found. Reporting ${LABEL} commit as 0.")
        return()
    elseif (NOT IS_DIRECTORY "${REPOSITORY_DIR}")
        message(WARNING "[SamdHealth] ${LABEL} directory '${REPOSITORY_DIR}' does not exist. Reporting commit as 0.")
        return()
    endif()

    execute_process(
        COMMAND "${GIT_EXECUTABLE}" rev-parse HEAD
        WORKING_DIRECTORY "${REPOSITORY_DIR}"
        RESULT_VARIABLE REV_PARSE_RESULT
        OUTPUT_VARIABLE COMMIT
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
    )
    # A detached/empty repository, a missing .git, or a shallow export all land here
    if (NOT REV_PARSE_RESULT EQUAL 0 OR NOT COMMIT MATCHES "^[0-9a-fA-F][0-9a-fA-F]+$")
        message(WARNING "[SamdHealth] Could not read HEAD of ${LABEL} at '${REPOSITORY_DIR}'. Reporting commit as 0.")
        return()
    endif()

    # Dirty state is reported in a comment only: SystemInfo has no field to carry it
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" status --porcelain --untracked-files=no
        WORKING_DIRECTORY "${REPOSITORY_DIR}"
        RESULT_VARIABLE STATUS_RESULT
        OUTPUT_VARIABLE STATUS_OUTPUT
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
    )
    if (STATUS_RESULT EQUAL 0 AND NOT STATUS_OUTPUT STREQUAL "")
        set(DIRTY_SUFFIX " (dirty)")
    else()
        set(DIRTY_SUFFIX "")
    endif()

    string(TOLOWER "${COMMIT}" COMMIT)
    string(LENGTH "${COMMIT}" COMMIT_LENGTH)
    if (COMMIT_LENGTH GREATER 16)
        string(SUBSTRING "${COMMIT}" 0 16 TRUNCATED_COMMIT)
    else()
        set(TRUNCATED_COMMIT "${COMMIT}")
    endif()

    set("${COMMIT_VAR}" "${TRUNCATED_COMMIT}" PARENT_SCOPE)
    set("${DESCRIPTION_VAR}" "${COMMIT}${DIRTY_SUFFIX}" PARENT_SCOPE)
endfunction()

foreach (REQUIRED_ARGUMENT IN ITEMS OUTPUT_FILE PROJECT_DIR FPRIME_DIR SAMD_DIR)
    if (NOT DEFINED "${REQUIRED_ARGUMENT}")
        message(FATAL_ERROR "[SamdHealth] GitVersion.cmake requires -D${REQUIRED_ARGUMENT}=<value>")
    endif()
endforeach()

samd_health_git_commit("${PROJECT_DIR}" "project" PROJECT_COMMIT PROJECT_DESCRIPTION)
samd_health_git_commit("${FPRIME_DIR}" "fprime" FPRIME_COMMIT FPRIME_DESCRIPTION)
samd_health_git_commit("${SAMD_DIR}" "fprime-samd" SAMD_COMMIT SAMD_DESCRIPTION)

get_filename_component(OUTPUT_NAME "${OUTPUT_FILE}" NAME)
get_filename_component(OUTPUT_STEM "${OUTPUT_FILE}" NAME_WE)
string(REGEX REPLACE "[^A-Za-z0-9]" "_" INCLUDE_GUARD "Samd21_${OUTPUT_STEM}_HPP")

set(GENERATED_HEADER
"// ======================================================================
// \\title  ${OUTPUT_NAME}
// \\brief  git commit stamps for the SamdHealth SystemInfo report
//
// AUTOGENERATED by fprime-samd/Drv/SamdHealth/GitVersion.cmake -- DO NOT EDIT
//
//   project     : ${PROJECT_DESCRIPTION}
//   fprime      : ${FPRIME_DESCRIPTION}
//   fprime-samd : ${SAMD_DESCRIPTION}
// ======================================================================

#ifndef ${INCLUDE_GUARD}
#define ${INCLUDE_GUARD}

#include <Fw/FPrimeBasicTypes.hpp>

namespace Samd21 {
namespace SamdHealthVersion {

//! Leading 64 bits of the project HEAD commit, or 0 if unavailable
static constexpr U64 PROJECT_COMMIT = 0x${PROJECT_COMMIT}ULL;

//! Leading 64 bits of the fprime framework HEAD commit, or 0 if unavailable
static constexpr U64 FPRIME_COMMIT = 0x${FPRIME_COMMIT}ULL;

//! Leading 64 bits of the fprime-samd library HEAD commit, or 0 if unavailable
static constexpr U64 SAMD_COMMIT = 0x${SAMD_COMMIT}ULL;

}  // namespace SamdHealthVersion
}  // namespace Samd21

#endif
")

# Only rewrite on change so that an unchanged stamp does not trigger a rebuild
if (EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" EXISTING_HEADER)
    if (EXISTING_HEADER STREQUAL GENERATED_HEADER)
        return()
    endif()
endif()
file(WRITE "${OUTPUT_FILE}" "${GENERATED_HEADER}")
