// ======================================================================
// \title  UsartDriverTester.hpp
// \author tumbar
// \brief  hpp file for UsartDriver test harness implementation class
// ======================================================================

#ifndef Samd21_UsartDriverTester_HPP
#define Samd21_UsartDriverTester_HPP

#include "fprime-samd/Drv/Types/StatusEnumAc.hpp"
#include "fprime-samd/Drv/Types/WritebackSerializableAc.hpp"
#include "fprime-samd/Drv/UsartDriver/UsartDriver.hpp"
#include "fprime-samd/Drv/UsartDriver/UsartDriverGTestBase.hpp"
#include "fprime-samd/Drv/UsartDriver/UsartDriverHardware.hpp"
#include "fprime-samd/Drv/UsartDriver/UsartDriver_DmaChannelEnumAc.hpp"

namespace Samd21 {

class UsartDriverTester : public UsartDriverGTestBase {
  public:
    // Maximum size for histories
    static constexpr FwSizeType MAX_HISTORY_SIZE = 100;

    // Test instance ID
    static constexpr FwEnumStoreType TEST_INSTANCE_ID = 0;

    // Stub SERCOM DATA register address returned by the HAL getDataRegisterAddress()
    static constexpr U32 DATA_REGISTER_ADDRESS = 0x42000428;

    // Construction and destruction
    UsartDriverTester();
    ~UsartDriverTester();

    // ----------------------------------------------------------------------
    // Tests
    // ----------------------------------------------------------------------

    // configure()
    void testConfigureNominal();
    void testConfigureAllParameters();
    void testConfigureQueuesRxBuffers();

    // send() / TX path
    void testSendNominal();
    void testSendQueueFull();
    void testSendCompletion();
    void testSendChannelError();

    // sendSync()
    void testSendSyncNominal();

    // RX path
    void testSchedInNoData();
    void testSchedInPartial();
    void testRxBufferDone();
    void testRxBufferFlip();
    void testRxMultiplePartials();
    void testRecvReturnIn();
    void testRxChannelError();

    // Unconfigured behavior
    void testSchedInUnconfigured();
    void testActiveInUnconfigured();

    // Trigger-source mapping
    void testTriggerSourceMapping();

  private:
    //! Component under test
    UsartDriver component;

    // ----------------------------------------------------------------------
    // Overridden output-port handlers
    // ----------------------------------------------------------------------

    //! Override for the dmaRxRead output port: returns a controllable
    //! writeback descriptor so tests can drive the "remaining beat count"
    //! that the driver uses to compute newly-received byte counts.
    Samd21::Dma::Writeback from_dmaRxRead_handler(FwIndexType portNum) override;

    // ----------------------------------------------------------------------
    // Helper functions
    // ----------------------------------------------------------------------

    //! Reset both the tester history and the stub hardware state
    void resetTest();

    //! Configure the component with the standard 115200 8N1 LSB-first setup.
    //! Also captures the two RX buffer base addresses from the dmaQueueOut
    //! history (destAddr of each RX transfer) so RX tests can validate the
    //! forwarded buffer pointers without touching the component's private state.
    void configureStandard();

    //! Base address (truncated as the driver does) of RX buffer A or B, as
    //! captured during configureStandard(). Index 0 == buffer A, 1 == buffer B.
    U32 rxBufferAddr(U32 index) const;

    //! Truncated data pointer of the recv() buffer at the given history index.
    //! Comparable against rxBufferAddr() to check which RX buffer/offset was
    //! forwarded downstream.
    U32 recvBufferAddr(U32 historyIndex) const;

    //! Set the remaining beat count reported by the next dmaRxRead_out() call
    void setRxRemainingBytes(U16 remaining);

    //! Invoke send() with a buffer and return the resulting sendReturnOut
    //! status once processed (helper drives the DMA completion + activeIn).
    void sendBuffer(Fw::Buffer& buffer);

    //! Simulate a DMA completion reply on the given channel (ISR context)
    void injectDmaReply(UsartDriver_DmaChannel channel, Samd21::Dma::Status::T status, U32 remainingBytes);

    //! Access the stub hardware state
    UsartHardware::StubState& stub();

    //! Connect ports (generated by UT_AUTO_HELPERS)
    void connectPorts();

    //! Initialize components (generated by UT_AUTO_HELPERS)
    void initComponents();

    //! Remaining beat count returned by the dmaRxRead handler
    U16 m_rx_remaining;

    //! Backing store for TX test buffers
    U8 m_tx_data[64];

    //! RX buffer base addresses captured from configure()'s dmaQueueOut calls
    U32 m_rx_buffer_addr[2];
};

}  // namespace Samd21

#endif
