// ======================================================================
// \title  I2cDriverTester.hpp
// \author tumbar
// \brief  hpp file for I2cDriver test harness implementation class
// ======================================================================

#ifndef Samd21_I2cDriverTester_HPP
#define Samd21_I2cDriverTester_HPP

#include "fprime-samd/Drv/I2cDriver/I2cDriver.hpp"
#include "fprime-samd/Drv/I2cDriver/I2cDriverGTestBase.hpp"
#include "fprime-samd/Drv/I2cDriver/I2cDriverHardware.hpp"
#include "fprime-samd/Drv/I2cDriver/I2cDriver_DmaChannelEnumAc.hpp"

namespace Samd21 {

class I2cDriverTester : public I2cDriverGTestBase {
  public:
    // Maximum size for histories
    static constexpr FwSizeType MAX_HISTORY_SIZE = 100;

    // Test instance ID
    static constexpr FwEnumStoreType TEST_INSTANCE_ID = 0;

    // Stub SERCOM DATA register address returned by the HAL getDataRegisterAddress()
    static constexpr U32 DATA_REGISTER_ADDRESS = 0x42001C28;

    // Construction and destruction
    I2cDriverTester();
    ~I2cDriverTester();

    // ----------------------------------------------------------------------
    // Tests
    // ----------------------------------------------------------------------

    // configure()
    void testConfigureNominal();
    void testConfigureAllParameters();
    void testConfigureRegistersIsr();

    // read()
    void testReadNominal();
    void testReadCompletion();
    void testReadBusy();

    // write()
    void testWriteNominal();
    void testWriteCompletion();
    void testWriteBusy();

    // writeRead()
    void testWriteReadNominal();
    void testWriteReadFullSequence();
    void testWriteReadBusy();
    void testWriteReadPointerNack();
    void testWriteReadMbAlreadyLatched();
    void testWriteReadMbAlreadyLatchedSpuriousIsr();

    // ISR error handling
    void testIsrErrorIdleUnexpected();
    void testIsrErrorDuringRead();
    void testIsrErrorDuringWrite();
    void testIsrErrorDuringWriteReadWriting();
    void testIsrErrorDuringWriteReadReading();
    void testIsrAllErrorFlags();

    // ISR master-on-bus handling
    void testIsrMasterOnBusUnexpected();

    // ISR error during write-read WAIT disables the MB interrupt (leak fix)
    void testIsrErrorDuringWriteReadWaitDisablesMb();

    // Stall watchdog (reportTelemetryIn)
    void testStallWatchdogNoRecoveryBeforeThreshold();
    void testStallWatchdogRecoversWriteRead();
    void testStallWatchdogRecoversRead();
    void testStallWatchdogRecoversWrite();
    void testStallWatchdogResetsWhenIdle();
    void testStallWatchdogResetsOnCompletion();
    void testStallRecoveryCountTelemetry();

    // dmaReplyIn channel validation
    void testDmaReplyWrongChannelRead();
    void testDmaReplyWrongChannelWrite();
    void testDmaReplyIdleIgnored();

    // Telemetry
    void testReportTelemetry();
    void testReportTelemetryDeviceOnBus();

    // Command
    void testClearErrors();

  private:
    //! Component under test
    I2cDriver component;

    // ----------------------------------------------------------------------
    // Helper functions
    // ----------------------------------------------------------------------

    //! Reset both the tester history and the stub hardware state
    void resetTest();

    //! Configure the component with a standard 100kHz two-wire setup.
    void configureStandard();

    //! Access the stub hardware state
    I2cHardware::StubState& stub();

    //! Simulate a DMA completion reply on the given channel (ISR context)
    void injectDmaReply(I2cDriver_DmaChannel channel, Samd21::Dma::Status::T status, U32 remainingBytes);

    //! Fire the SERCOM ISR after arming an error/interrupt state in the stub.
    void fireIsr();

    //! Drive the activeIn port (main-context tick) that delivers a pending
    //! transaction completion to the client. Returns whether a completion was
    //! delivered this tick.
    bool driveActiveIn();

    //! Truncated 32-bit address of a buffer's data, matching how the driver
    //! passes buffer pointers to the DMA transaction port.
    static U32 bufferAddr(const U8* data);

    //! Connect ports (generated by UT_AUTO_HELPERS)
    void connectPorts();

    //! Initialize components (generated by UT_AUTO_HELPERS)
    void initComponents();

    //! Backing store for test buffers
    U8 m_write_data[64];
    U8 m_read_data[64];
};

}  // namespace Samd21

#endif
