// ======================================================================
// \title  AdcDriverTester.hpp
// \author crsmith
// \brief  hpp file for AdcDriver test harness implementation class
// ======================================================================

#ifndef Samd21_AdcDriverTester_HPP
#define Samd21_AdcDriverTester_HPP

#include "fprime-samd/Drv/AdcDriver/AdcDriver.hpp"
#include "fprime-samd/Drv/AdcDriver/AdcDriverGTestBase.hpp"
#include "fprime-samd/Drv/AdcDriver/AdcDriverHardware.hpp"

namespace Samd21 {

class AdcDriverTester : public AdcDriverGTestBase {
  public:
    // Maximum size for histories
    static constexpr FwSizeType MAX_HISTORY_SIZE = 100;

    // Test instance ID
    static constexpr FwEnumStoreType TEST_INSTANCE_ID = 0;

    // Construction and destruction
    AdcDriverTester();
    ~AdcDriverTester();

    // ----------------------------------------------------------------------
    // Tests
    // ----------------------------------------------------------------------

    // configure()
    void testConfigure();
    void testConfigureAllReferences();
    void testConfigureAllResolutions();
    void testConfigureAllSampleCounts();
    void testConfigureAllGains();

    // configureChannel()
    void testConfigureChannelNominal();

    // ADC conversion: error cases (readAdc validation)
    void testConversionNotConfigured();
    void testConversionChannelNotConfigured();
    void testConversionBusy();

    // ADC conversion: completion flow (full end-to-end)
    void testConversionCompletion();
    void testConversionMultipleChannels();
    void testConversionResultBoundaries();

    // ADC conversion: edge cases
    void testConversionBeforeComplete();
    void testConversionMultipleactiveInIdle();

    // ISR / handleInterrupt()
    void testHandleInterruptResultReady();
    void testHandleInterruptOverrun();
    void testHandleInterruptBothFlags();
    void testHandleInterruptNoFlags();
    void testHandleInterruptMultipleTimes();
    void testHandleInterruptWithoutPendingConversion();
    void testHandleInterruptSpuriousWithOverrun();

  private:
    //! Component under test
    AdcDriver component;

    // ----------------------------------------------------------------------
    // Helper functions
    // ----------------------------------------------------------------------

    //! Reset both the tester history and the stub hardware state
    void resetTest();

    //! Reset the singleton instance pointer (for testing multiple configurations)
    void resetSingleton();

    //! Configure the component with standard INT1V reference, 12-bit resolution
    void configureStandard();

    //! Simulate ADC conversion complete by injecting hardware state and calling ISR
    void simulateConversionComplete(U32 result);

    //! Simulate ADC overrun by injecting hardware state and calling ISR
    void simulateOverrun();

    //! Access the stub hardware state
    AdcHardware::StubState& stub();

    //! Helper to assert ADC result with both value and status
    void assertAdcResult(FwSizeType size, FwIndexType index, U32 expectedValue, Samd21::AdcStatus expectedStatus);

    //! Connect ports (generated by UT_AUTO_HELPERS)
    void connectPorts();

    //! Initialize components (generated by UT_AUTO_HELPERS)
    void initComponents();
};

}  // namespace Samd21

#endif
